### ISSUE TITLE
Student Registration

### ISSUE THREAD

**Issue by catherinereyeslao** [catherinereyeslao/Thesis#1]
When a user registers as a student, username should not be overwritten when another user with the same name registers. 
Possible solutions: 
-Password (eto ung pinakamadaling gawin hehe)
-alert the user that an existing account is registered therefore asking the user to change the username he/she entered
-Require a specific ID format

**Comment by johnelauria** [comment]
Option 1: Type name & password in 1 screen
![login-option1](https://cloud.githubusercontent.com/assets/1751349/6430032/9061bada-c031-11e4-841c-4b00044648d8.jpg)

Option 2.1: Type name first same as before, then type password on next screen
![login](https://cloud.githubusercontent.com/assets/1751349/6430031/905edae0-c031-11e4-96c0-6ab1e98b7df0.png)

Option 2.2: Type password here after typing the username
![login-option2-1](https://cloud.githubusercontent.com/assets/1751349/6430033/9066b5f8-c031-11e4-892c-8fa26244edcd.jpg)

After enter ng credentials & ndi pa existing yung user, lalabas yung Alert box pra iconfirm kung mag reregister as new user. Pag existing ung user & match sa password, derecho login na.
