### ISSUE TITLE
Remove Swipe to next page feature

### ISSUE THREAD

**Issue by catherinereyeslao** [catherinereyeslao/Thesis#7]
put a previous and next button instead of swiping to next page.

**Comment by johnelauria** [comment]
All lectures will have left & right arrow for back & next respectively. Back arrow not displayed if viewing 1st lecture. Next arrow not displayed if viewing last chapter 

![issue7](https://cloud.githubusercontent.com/assets/1751349/6595750/10935e5e-c828-11e4-878b-060ad64082c3.png)

Ok ba to?

**Comment by catherinereyeslao** [comment]
Yup kuya okay na po yan
